"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
import django
from dotenv import load_dotenv
from pathlib import Path

print({key: os.environ[key] for key in os.environ if "NEXT" in key})

RECAPTCHA_CREDENTIALS = os.getenv("RECAPTCHA_CREDENTIALS")
NEXT_RECAPTCHA_PUBLIC_KEY = os.getenv("NEXT_RECAPTCHA_PUBLIC_KEY")
RECAPTCHA_SECRET_KEY = os.getenv("RECAPTCHA_SECRET_KEY")
RECAPTCHA_VERIFY_URL = os.getenv("RECAPTCHA_VERIFY_URL")
RECAPTCHA_PROJECT = os.getenv("RECAPTCHA_PROJECT")
SMSSERVER_TOKEN = os.getenv("SMSSERVER_TOKEN")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(os.path.join(BASE_DIR, '.env.backend'))

# Superuser configuration
SUPERUSER_USERNAME = os.getenv("DJANGO_SUPERUSER_USERNAME")
SUPERUSER_EMAIL = os.getenv("DJANGO_SUPERUSER_EMAIL")
SUPERUSER_PASSWORD = os.getenv("DJANGO_SUPERUSER_PASSWORD")

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']  # This should point to your 'static' directory
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Use this in production
DEBUG_PROPAGATE_EXCEPTIONS = True

print(django.__path__)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-z6(s*@zbgk8%esa-h(i*7$ql0z4_$n5ayqccsfw&ur#o5u5#ng')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False').lower() == 'false'

# PRODUCTION
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
SECURE_BROWSER_XSS_FILTER = not DEBUG
SECURE_CONTENT_TYPE_NOSNIFF = not DEBUG
SECURE_SSL_REDIRECT = not DEBUG  # Ensure your site uses HTTPS

# ALLOWED_HOSTS = ['127.0.0.1', 'localhost'] or ['*'] for development
ALLOWED_HOSTS = [
    'psychsys-backend-aeb8bb98bb68.herokuapp.com',
    'psychsys-nginx-a1f751d771b5.herokuapp.com',  # Add all relevant hostnames
    '127.0.0.1',  # Local development
    'localhost',  # Local development
    'psychoterapia-systemowa.pl'
]

CORS_ALLOWED_ORIGINS = [
    'https://psychoterapia-systemowa.pl'
    'https://psychsys-nginx-a1f751d771b5.herokuapp.com'
]

CSRF_TRUSTED_ORIGINS = [
   'https://psychoterapia-systemowa.pl'
   'https://psychsys-nginx-a1f751d771b5.herokuapp.com'
]

# Application definition

INSTALLED_APPS = [
    'appointment',
    'django_celery_beat',
    'corsheaders',
    'django_extensions',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles'
]

MIDDLEWARE = [
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

MIDDLEWARE.insert(0, 'corsheaders.middleware.CorsMiddleware')

CORS_ALLOW_ALL_ORIGINS = True  # Allow all origins for testing (use a specific origin in production)
CORS_ALLOW_CREDENTIALS = True
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True


ROOT_URLCONF = 'backend.urls'


REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

print("BASE_DIR:", BASE_DIR)


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# AUTH_USER_MODEL = 'models.UserModel'  # Optional if you use Django's user model

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Or to allow all origins (not recommended for production)
# CORS_ALLOW_ALL_ORIGINS = True

# CELERY TASKS
# backend/settings.py

CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Update this as per your Redis configuration
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'  # Adjust if needed
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
