services:
  django:
    build: .
    container_name: django-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - app-network
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=*

  nextjs:
    build:
      context: .
      dockerfile: nextfrontend/Dockerfile
    container_name: nextjs-app
    ports:
      - "3000:3000"
    volumes:
      - ./nextfrontend:/app
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
      - ./media:/media
    networks:
      - app-network
    depends_on:
      - django
      - nextjs

networks:
  app-network:
    driver: bridge
