services:
  django:
    build:
      context: psychsys-backend
      dockerfile: Dockerfile
    image: kanies/django_website-django:latest
    container_name: django-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - app-network
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=psychoterapia-systemowa.pl,psychsys-frontend-fde1b2b544e7.herokuapp.com

  nextjs:
    build:
      context: psychsys-frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: "./api/"
        NEXT_PUBLIC_RECAPTCHA_PUBLIC_KEY: "6LePVqwqAAAAABj50TNS5cVYvfpInY5Cc5sET_Nb"
    image: kanies/django_website-nextjs:latest
    container_name: nextjs-app
    ports:
      - "3000:3000"
    depends_on:
      - django-app
    volumes:
      - ./psychsys-frontend:/app
    networks:
      - app-network


  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
      - ./media:/media
    networks:
      - app-network
    depends_on:
      - django
      - nextjs

networks:
  app-network:
    driver: bridge
