name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main
  workflow_dispatch: #manual
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH key for PythonAnywhere
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PYTHONANYWHERE_SSH_KEY }}
        SSH_KEY_PASSWORD: ${{ secrets.SSH_KEY_PASSWORD }}
      run: |
        # Create the .ssh directory if it doesn't exist
        mkdir -p ~/.ssh
        
        # Save the SSH private key to a file
        echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
        # Start the SSH agent and add the private key with the passphrase
        eval $(ssh-agent -s)
        echo "${SSH_KEY_PASSWORD}" | ssh-add ~/.ssh/id_rsa
        
        # Add PythonAnywhere to known hosts to prevent SSH prompts
        ssh-keyscan -H ssh.pythonanywhere.com >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Deploy to PythonAnywhere
      run: |
        # Start the SSH agent
        eval $(ssh-agent -s)
    
        # Add the private key to the SSH agent (assuming you also have the passphrase in secrets)
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add - <<< "${{ secrets.SSH_KEY_PASSWORD }}"
    
        # Add PythonAnywhere to known hosts to prevent SSH prompts
        mkdir -p ~/.ssh
        ssh-keyscan -H ssh.pythonanywhere.com >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
    
        # SSH into PythonAnywhere and deploy your app
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -T ${{ secrets.PYTHONANYWHERE_USERNAME }}@ssh.pythonanywhere.com << 'EOF'
        cd /home/username/myapp
        git pull origin main
        source venv/bin/activate
        pip install -r requirements.txt
        python manage.py migrate
        touch reload.ini
        EOF
