name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH Key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PYTHONANYWHERE_KEY }}
      run: |
        echo "${SSH_PRIVATE_KEY}" > deploy_key
        chmod 600 deploy_key
        # Start SSH agent
        eval $(ssh-agent -s)
        # Add the private key to the agent
        echo "${{ secrets.SSH_KEY_PASSWORD }}" | ssh-add deploy_key

    - name: Add PythonAnywhere to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ssh.pythonanywhere.com >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Deploy to PythonAnywhere
      run: |
        ssh -i deploy_key -o StrictHostKeyChecking=no psychoterapiasystemowa@ssh.pythonanywhere.com << 'EOF'
        mkdir -p ~/webpage
        cd ~/webpage
        git pull
        source venv/bin/activate
        pip install -r requirements.txt
        python manage.py migrate
        touch reload.ini
        EOF
