name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH key for PythonAnywhere
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PYTHONANYWHERE_SSH_KEY }}
      run: |
        # Save the SSH private key to a file
        echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
        # Start the SSH agent and add the private key
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/id_rsa
        
        # Add PythonAnywhere to known hosts to prevent SSH prompts
        mkdir -p ~/.ssh
        ssh-keyscan -H ssh.pythonanywhere.com >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Deploy to PythonAnywhere
      env:
        PYTHONANYWHERE_USERNAME: ${{ secrets.PYTHONANYWHERE_USERNAME }}
      run: |
        # SSH into PythonAnywhere and deploy your app
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.PYTHONANYWHERE_USERNAME }}@ssh.pythonanywhere.com << 'EOF'
        cd /home/${{ secrets.PYTHONANYWHERE_USERNAME }}/ps_app
        git pull origin main
        source venv/bin/activate
        pip install -r requirements.txt
        python manage.py migrate
        touch reload.ini
        EOF
